# Generated by Django 2.2.24 on 2022-01-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='klaxs',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.Klaxcoin'),
            preserve_default=False,
        ),
    ]
